# Generated by Django 4.2.1 on 2023-05-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_user_delete_customuser_candidate_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
